### ISSUE TITLE
synth in MOOG is not working

### ISSUE THREAD

**Issue by Mohammad-Mardini** [alexji/moog17scat#1]
Hi Alexji,

I followed your instructions on MacBook Pro (High Sierra 10.13.6) and it went well.
I tried to use synth in MOOG, but it didn't work properly. Instead, my terminal started to flash.
I think there is something wrong with X11, I'm using XQuartz since X11 is not available on Mac anymore.
Could you please help me with this issue?
Thank you in advance for your help and time.

**Comment by alexji** [comment]
Hi Mohammad-Mardini,

The default version I have does not work with the GUI/supermongo version of
MOOG (since I only use MOOGSILENT). That could be the source of your
problems.

There is a branch "with-sm" that has supermongo included, though I have not
tested it and have not had a chance to merge it with the master version's
latest bugfixes.

If it's something else, then I'm afraid I have no idea what's going on!

-Alex

**Comment by Mohammad-Mardini** [comment]
Thank you for your reply, I will close this issue
